application: oxfordpubcrawl
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets
  static_dir: assets

- url: /auth.*
  script: src.auth.app

- url: /admin.*
  script: src.admin.app
  login: admin

- url: /ajax.*
  script: src.ajax.app

- url: .*
  script: src.main.app

libraries:
- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: latest

admin_console:
  pages:
    - name: Add Pub
      url: /admin/addpub
    - name: Clear Invalid Visits
      url: /admin/clean

